### ISSUE TITLE
dúvida sobre SEED

### ISSUE THREAD

**Issue by rabugento** [joaocampinhos/Primedice.js#1]
Olá João,

Tenho uma dúvida sobre a função seed. 
Vi que precisa atribuir um hash na função, para que a função troque o seed.
Não teria como a própria função fazer uma requisição de seed no servidor e trocar o seed automaticamente?
No momento estou entrando no site só para pegar o hash de um novo seed para usar a função.

**Comment by joaocampinhos** [comment]
Olá,

Trocar o seed automaticamente para um novo hash aleatório? como acontece no site se carregarmos em **Rerandomize**? É se for isso basta arranjar uma forma de criar hash aleatórios (até devem existir módulos que façam isso)

**Comment by rabugento** [comment]
Olá João,

Obrigado pela resposta rápida. 
É exatamente isso. Seria bom se a função seed pudesse criar aleatoriamente um novo hash e aplicar como novo seed. Isso daria mais chances de acertos no jogo.
Não tenho ideia de como pode ser feito isso, e fica a dica para adicionar no seu projeto.

**Comment by joaocampinhos** [comment]
Acho melhor deixar a criação de hash para outros módulos. Vou fechar mas deixo aqui um exemplo de como pode ser feito isso utilizando o módulo [chance](http://chancejs.com/#hash):

``` javascript
var Primedice = require('Primedice');
var Chance = require('chance');
var accessToken = 'abc123';

var client = new Primedice(accessToken);
var chance = new Chance();

Primedice.seed(chance.hash(), function(error, response) {
  if (!err) console.log(response);
});
```
